name: Perl Tester Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: On host
      run: hostname

  test:
    container:
      image: perldocker/perl-tester:latest     # https://hub.docker.com/r/perldocker/perl-tester
    steps:
    - name: In container
      run: hostname
