name: Push and schedule

on:
  push:
    branches: '*'
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Single step
      run: |
        echo Hello World
        echo $GITHUB_EVENT_NAME

    - name: Look around
      run: |
        printenv | sort

    - name: Conditional step
      if: env.GITHUB_EVENT_NAME == 'schedule'
      run: |
        echo "Only run in schedule"

    - name: Step after
      run: |
        echo "Always run"

